### ISSUE TITLE
Refresh forever

### ISSUE THREAD

**Issue by eitanshp** [eedevops/shipyard#116]
Regression:
Hitting project results starts the spinner that spins forever.
Going to another tab (containers, images) shows the data in the background but the spinner is still in the foreground, showing no data.
Moreover, you'll never get the actual project results.
To repro:
http://ec2-52-37-174-113.us-west-2.compute.amazonaws.com:8082/#/projects
Click on a project's results. It will show you the table (or get stuck at that point). Hit one of the test results - spins forever.

**Comment by soninob** [comment]
@eitanshp - did you check the latest and greatest? please check with @edagan, he has is on a different machine.

**Comment by eitanshp** [comment]
@soninob - checked on the latest and greatest, as instructed by @edagan.

**Comment by soninob** [comment]
Thanks, @AndreeaDora - please check it.

**Comment by rqc** [comment]
@eitanshp this is related to the **known** issue in the backend with the database connections. Since we have a lot of different result objects to maintain as per the API, we are making several queries to the db in separate goroutines (threads), and at some point the queries are hanging. @JonathanRosado is working on fixing this, he spotted some instances in which the db descriptors were not being closed. We will see if this fixes the issue for good.

**Comment by rqc** [comment]
@eitanshp this is referenced here https://github.com/eedevops/shipyard/issues/115

**Comment by eitanshp** [comment]
@rqc - this is new (never seen it before).
Moreover, why going to a different tab doesn't reset the UI to stop polling the BE?

**Comment by JonathanRosado** [comment]
@eitanshp When the Rethink session decides to *hang*. All subsequent queries to the db will also hang.

For the frontend, this means that the user will be greeted with a loading screen (since the requests to the backend remain open)

Here are some similar issue [171](https://github.com/dancannon/gorethink/issues/171) and [180](https://github.com/dancannon/gorethink/issues/180)

Currently testing the fix

**Comment by rqc** [comment]
@eitanshp I had seen this before in the UI. There are two things here. The db issues, which have resurfaced a bug in the UI. I think the UI issue might be that since the request never returns any data, the state of the spinner overlay never gets reset when you change views. I had talked to @JonathanRosado a while back about this UI behavior but we couldn't replicate it.

**Comment by eitanshp** [comment]
Easily replicatable now on 113...



On Wed, May 18, 2016 at 7:37 AM -0700, "Ricardo Quintana" <notifications@github.com<mailto:notifications@github.com>> wrote:


@eitanshp<https://github.com/eitanshp> I had seen this before in the UI. There are two things here. The db issues, which have resurfaced a bug in the UI. I think the UI issue might be that since the request never returns any data, the state of the spinner overlay never gets reset when you change views. I had talked to @JonathanRosado<https://github.com/JonathanRosado> a while back about this UI behavior but we couldn't replicate it.

-
