### ISSUE TITLE
how to use the demo branch?

### ISSUE THREAD

**Issue by kazaff** [eedevops/shipyard#154]
i am a newbie, somebody can give me a detail to let it work? or an article that let me read?~

thanks all~

**Comment by edagan** [comment]
Hi Kazaff,  
  
Please see our Wiki -   
* The demo branch deployment instructions are [here](https://github.com/eedevops/shipyard/wiki/Deployment-Instructions). Checkout the demo branch instead of dev branch, as needed.  
* An easy build and deployment script is currently available on the dev branch only. Instructions are [here](https://github.com/eedevops/shipyard/wiki/How-to-build,-test-and-deploy-ILM-via-Buildme.sh).  
  
We are preparing a new Wiki page which will explain how to use our pre-generated images off docker hub. 

Please feel free to contact me with any issues or questions.

**Comment by kazaff** [comment]
@edagan  thank you soooooo much~
