### ISSUE TITLE
shipyard-ready-registry-v2 ,Can not add registry2.

### ISSUE THREAD

**Issue by yeruisen** [eedevops/shipyard#185]
When I add registry2,
the registry response : 
```
level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host=registry.com http.request.id=8faa30ab-0562-4fb0-abb7-78220d34a32d http.request.method=GET http.request.remoteaddr=172.17.0.1 http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=1570ed8c-8495-49ec-be24-526b598e3e1e version=v2.3.1
172.17.0.6 - - [23/Aug/2016:10:15:59 +0800] "GET /v2/ HTTP/1.0" 401 87 "" "Go-http-client/1.1"
```

**Comment by AndreeaDora** [comment]
@yeruisen It seems that you are trying to set up an registry and you are not able to log in to it. Please try to check it using `docker login [SERVER]`. 
The `--insecure-registry` needs to be set in the `/etc/default docker`. In case you have ubuntu version 16.04 you need to configure it for systemd. 
Keep in mind that is not possible to use insecure registry with basic authentication.

**Comment by yeruisen** [comment]
@AndreeaDora 
Yes, I agree with you. but it didn't work.
because my registry2.0 was controlled by Portus. So I don't know what to do.

**Comment by AndreeaDora** [comment]
@yeruisen It sounds that it is a problem with the registry deployed in Portus and not with ILM. I suggest you try to make the registry work using `docker login [SERVER]`, and then add it to the shipyard registries.

**Comment by rqc** [comment]
@yeruisen in the host where you have deployed `eedevops/shipyard` (ILM) check the `docker daemon` configuration. I suggest you take a look at the following [docker docs](https://docs.docker.com/v1.10/engine/reference/commandline/daemon/). Basically, you need to configure your host's `docker daemon` so that it overrides the requirement from the client to *verify TLS*. This is done with the flag `--insecure-registry=[]` (from the documentation before).

Another option, if you are using an `ubuntu` host, you may also configure the `daemon` in the `/etc/default/docker` file by adding the above flag to the `DOCKER_OPTS` environment variable. After that you need to restart your `docker daemon` by restarting the service (e.g. `sudo service docker restart`. 

I hope that helps!

**Comment by rqc** [comment]
Referencing https://github.com/eedevops/shipyard/issues/77 which is an open, known issue. @soninob @edagan you might want to come up with an automated way to send this configuration to the `docker daemon` *upon registry addition*.

**Comment by yeruisen** [comment]
@AndreeaDora
@rqc 
Yes， the problem  due to the registry deployed in Portus and not ILM.  So I plan to solve this problem from Portus.

**Comment by soninob** [comment]
Closing, @yeruisen if there is still a need for this issue, please reopen.
