### ISSUE TITLE
[UI] -Running inspect on not tested project shows error

### ISSUE THREAD

**Issue by soninob** [eedevops/shipyard#55]
"It looks like an error occurred:"

**Comment by JonathanRosado** [comment]
@soninob Thanks, i'm able to replicate this issue. That said, how should we proceed?
Here are a couple of possible solutions:
- Disable inspect button if the project is not yet built. We can even add a tool-tip with instructions on how to build the project.
- Instead of the default `error` view, we can display one that explains why the error pops up and how to fix it. Possibly adding some steps and/or links.

**Comment by soninob** [comment]
@JonathanRosado I agree with the first point, disabling **and** a tool tip. @edagan - WDYT?

**Comment by edagan** [comment]
@JonathanRosado, @soninob - Agreed. Disabling the button with a tooltip info popup is great.
