### ISSUE TITLE
Removing URL from controller command

### ISSUE THREAD

**Issue by soninob** [eedevops/shipyard#7]
Need to work with environment variable instead of using hard coded URL.
Also, we need to make sure that we are dealing with the case of there is no such env var and prompt with the right message.
I suggest to replace the command with something like that:
command: server -d ${SHIPYARD_SWARM_ENDPOINT}

**Comment by rqc** [comment]
Hello, what's the status of this? @borzamircea @AndreeaDora

**Comment by rqc** [comment]
I just saw this branch which has a solution for the external swarm. https://github.com/eedevops/shipyard/commits/wip/docker-compose-changes

The part about the proxy settings is no longer applicable since we are using the `.env` file. But we should definitely use an environment variable for the `controller` `command`. I would actually use something like `$SHIPYARD_SWARM_ENDPOINT` (as @soninob suggested) instead of `$SWARM` to make sure that we don't have env var collisions.
