### ISSUE TITLE
[UI] Missing link from results page back to Edit Project page

### ISSUE THREAD

**Issue by edagan** [eedevops/shipyard#82]
Can't quickly switch between Project Edit and Project Results views.

**Comment by soninob** [comment]
@edagan - do you have any suggestion on where to put it? How would it look?
Do we want to take it with the Dolly or wait with it post June?

**Comment by edagan** [comment]
Top right of page, Under "Go To Projects", works for me.
We should consult with Dolly for best placement, however.

**Comment by soninob** [comment]
hmmm, two 'go to' buttons on the same space can be confusing, what about 'divide and conquer' - one of the buttons can be on the bottom on the other side of the table. @edagan WDYT?

**Comment by edagan** [comment]
@soninob Whatever you fee looks best - just let me quickly navigate between the views, please :)

**Comment by AndreeaDora** [comment]
Guys, here is what I implemented:
![image](https://cloud.githubusercontent.com/assets/12065220/15249337/b23c2898-1927-11e6-81e4-0f103851aab0.png)
What do you think?

**Comment by rqc** [comment]
I still find it confusing that we can jump to the results view for a project from the project list, I think that by first going to a `Project View` that allows you to switch between the `Edit View` and the `Results View`. 

I think the navigation should follow a more-tree like path structure. This is design pattern that is heavily used and well known by users. Right now, if you do try to do this you can't:
1. Go to project list view
2. Click on magnifying glass (results)
3. Go to Project Edit Link
4. I am in Project Edit View 
5. I want to look at results, but I can't

So, what I recommend is: 
1. Remove magnifying glass from project list view 
2. Instead make the list items linkable, to follow a more navigational feel
3. When you go to the `Edit View` it should look more like a `Profile View` that has a way to switch or drill down to the Results.
4. If you choose a drill down mechanism, then you can use a link like the one above. If you use more of a switch view (like tabs) then you don't need it because you will have the tabs available.

Hope that helps!

**Comment by soninob** [comment]
Thank you @rqc.
Removing magnifying glass will eliminate the option to show results page in one click, which I'm against that.
We have an item to allow jumping to results from the edit view.
@AndreeaDora - I would suggest that the label you added will be changed to a small button with only "Edit Project".

**Comment by AndreeaDora** [comment]
@soninob I did the changes that you requested:
![image](https://cloud.githubusercontent.com/assets/12065220/15288806/49dd06e0-1b76-11e6-8df9-516e858176de.png)
As @rcq mentioned, we should have a tree like path for the navigation. Right now the user could get confused because he is able to go edit the project from the project results view, but he can not go back to the project results view directly from the edit view. 
The action item we have in the edit view can be used to get to the project results view or to the test result view:
![image](https://cloud.githubusercontent.com/assets/12065220/15288938/3d2e2e32-1b77-11e6-8fcd-ba32e4cbf244.png)
I would suggest to use it to get to the test result view.
